/**
 * upgraded-server.js - T-Shirt Customizer Backend with InstantID (Polling Loop Version)
 */

import express from "express";
import cors from "cors";
import fetch from "node-fetch";

const app = express();
const PORT = process.env.PORT || 3000;

// Replicate API Configuration
const REPLICATE_API_KEY = process.env.REPLICATE_API_KEY; 
const REPLICATE_ENDPOINT = "https://api.replicate.com/v1/predictions";
const INSTANT_ID_MODEL = "cb4a30;b7f6ff46f8832a;2e964f43b593ef908"; // The key for InstantID

app.use(cors());
app.use(express.json());

app.post("/api/tshirt-preview", async (req, res) => {
  const { customerImageUrl, maskUrl, referenceStyleUrl } = req.body;

  if (!customerImageUrl || !maskUrl) {
    return res.status(400).json({ error: "Missing required customerImageUrl or maskUrl." });
  }

  const inputPromptImage = referenceStyleUrl || "https://res.cloudinary.com/dugxzgkvy/image/upload/v1783858281/1000113069_l18mfk.png";

  try {
    console.log(`Starting generation with InstantID for user image: ${customerImageUrl}`);

    // Step 1: Tell Replicate to start the job
    const startResponse = await fetch(REPLICATE_ENDPOINT, {
      method: "POST",
      headers: {
        "Authorization": `Token ${REPLICATE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        version: INSTANT_ID_MODEL,
        input: {
          image_prompt_method: "ip-adapter", 
          input_image: customerImageUrl,      
          prompt: "A high-quality studio portrait of the person, integrated perfectly as the subject.",
          negative_prompt: "hallucination, text, distorted face, different ethnicity, artifacts",
          num_outputs: 1,
          mask: maskUrl,                      
          structure_image: inputPromptImage,  
          face_detailer: true,                
          controlnet_weights: "0.8",          
          disable_safety_checker: true       
        }
      })
    });

    let replicateData = await startResponse.json();
    if (replicateData.error) throw new Error(replicateData.error);

    // Step 2: The Polling Loop (Keep checking until it is finished)
    const checkStatusUrl = replicateData.urls.get;
    let status = replicateData.status;

    console.log("AI is processing. Waiting for completion...");

    while (status !== "succeeded" && status !== "failed") {
      // Wait for 2 seconds before asking again
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const pollResponse = await fetch(checkStatusUrl, {
        headers: {
          "Authorization": `Token ${REPLICATE_API_KEY}`,
          "Content-Type": "application/json"
        }
      });
      
      replicateData = await pollResponse.json();
      status = replicateData.status;
      console.log(`Current status: ${status}`);
    }

    // Step 3: Handle the final result
    if (status === "failed") throw new Error("Replicate AI generation failed during processing.");
    if (!replicateData.output || !replicateData.output[0]) throw new Error("No image output generated by the AI.");

    const outputUrl = replicateData.output[0];
    console.log(`Generation complete. AI Image URL: ${outputUrl}`);
    
    res.json({ aiImageUrl: outputUrl });

  } catch (error) {
    console.error("AI Generation Error:", error.message);
    res.status(500).json({ error: error.message || "An unexpected error occurred." });
  }
});

app.listen(PORT, () => {
  console.log(`Upgraded Customizer Server running on port ${PORT}`);
});
