/**
 * upgraded-server.js - T-Shirt Customizer Backend (Robust Error Catching)
 */

import express from "express";
import cors from "cors";
import fetch from "node-fetch";

const app = express();
const PORT = process.env.PORT || 3000;

// Replicate API Configuration
const REPLICATE_API_KEY = process.env.REPLICATE_API_KEY; 
const REPLICATE_ENDPOINT = "https://api.replicate.com/v1/predictions";

// The official, verified Replicate InstantID version hash
const INSTANT_ID_MODEL = "2e4785a4d80dadf580077b2244c8d7c05d8e3faac04a04c02d8e099dd2876789"; 

app.use(cors());
app.use(express.json());

app.post("/api/tshirt-preview", async (req, res) => {
  const { customerImageUrl, maskUrl, referenceStyleUrl } = req.body;

  if (!customerImageUrl || !maskUrl) {
    return res.status(400).json({ error: "Missing required customerImageUrl or maskUrl." });
  }

  try {
    console.log(`Starting generation for user image: ${customerImageUrl}`);

    // Step 1: Tell Replicate to start the job
    const startResponse = await fetch(REPLICATE_ENDPOINT, {
      method: "POST",
      headers: {
        "Authorization": `Token ${REPLICATE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        version: INSTANT_ID_MODEL,
        input: {
          image: customerImageUrl, // Standard InstantID uses 'image'
          prompt: "A high-quality studio portrait of the person, integrated perfectly as the subject.",
          negative_prompt: "hallucination, text, distorted face, different ethnicity, artifacts"
        }
      })
    });

    // 🚨 THE FIX: Catch Replicate's HTTP rejections before the app crashes
    if (!startResponse.ok) {
      const errorText = await startResponse.text();
      console.error("Replicate API Rejected the Request:", errorText);
      throw new Error(`Replicate API Error: ${errorText}`);
    }

    let replicateData = await startResponse.json();

    // Step 2: The Polling Loop
    const checkStatusUrl = replicateData.urls.get;
    let status = replicateData.status;

    console.log("AI is processing. Waiting for completion...");

    while (status !== "succeeded" && status !== "failed") {
      await new Promise(resolve => setTimeout(resolve, 2000)); // wait 2 seconds
      
      const pollResponse = await fetch(checkStatusUrl, {
        headers: {
          "Authorization": `Token ${REPLICATE_API_KEY}`,
          "Content-Type": "application/json"
        }
      });
      
      replicateData = await pollResponse.json();
      status = replicateData.status;
      console.log(`Current status: ${status}`);
    }

    // Step 3: Handle the final result
    if (status === "failed") throw new Error("Replicate AI generation failed during processing.");
    if (!replicateData.output || !replicateData.output[0]) throw new Error("No image output generated by the AI.");

    const outputUrl = replicateData.output[0];
    console.log(`Generation complete. AI Image URL: ${outputUrl}`);
    
    res.json({ aiImageUrl: outputUrl });

  } catch (error) {
    console.error("AI Generation Error:", error.message);
    res.status(500).json({ error: error.message || "An unexpected error occurred." });
  }
});

app.listen(PORT, () => {
  console.log(`Upgraded Customizer Server running on port ${PORT}`);
});
