/**
 * upgraded-server.js - T-Shirt Customizer Backend with InstantID (Final ES Module)
 */

import express from "express";
import cors from "cors";
import fetch from "node-fetch";

const app = express();
const PORT = process.env.PORT || 3000;

// Replicate API Configuration
const REPLICATE_API_KEY = process.env.REPLICATE_API_KEY; 
const REPLICATE_ENDPOINT = "https://api.replicate.com/v1/predictions";
const INSTANT_ID_MODEL = "cb4a30;b7f6ff46f8832a;2e964f43b593ef908"; // The key for InstantID

app.use(cors());
app.use(express.json());

app.post("/api/tshirt-preview", async (req, res) => {
  const { customerImageUrl, maskUrl, referenceStyleUrl } = req.body;

  // Safety Checks: Must have both images
  if (!customerImageUrl || !maskUrl) {
    return res.status(400).json({ error: "Missing required customerImageUrl or maskUrl." });
  }

  // Use referenceStyleUrl if provided, otherwise default to the provided ADYA design
  const inputPromptImage = referenceStyleUrl || "https://res.cloudinary.com/dugxzgkvy/image/upload/v1783858281/1000113069_l18mfk.png";

  try {
    console.log(`Starting generation with InstantID for user image: ${customerImageUrl}`);

    // Call Replicate API for high-fidelity face transfer
    const response = await fetch(REPLICATE_ENDPOINT, {
      method: "POST",
      headers: {
        "Authorization": `Token ${REPLICATE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        version: INSTANT_ID_MODEL,
        input: {
          image_prompt_method: "ip-adapter", // High-fidelity face preservation
          input_image: customerImageUrl,      // The target identity face
          prompt: "A high-quality studio portrait of the person, integrated perfectly as the subject.",
          negative_prompt: "hallucination, text, distorted face, different ethnicity, artifacts",
          num_outputs: 1,
          mask: maskUrl,                      // Your perfectly locked mask
          structure_image: inputPromptImage,  // The overall t-shirt design reference
          face_detailer: true,                // Extra focus on maintaining face structure
          controlnet_weights: "0.8",          // How strong to force the identity transfer (higher is stricter)
          disable_safety_checker: true       // Essential for clothing/human transfer
        }
      })
    });

    const replicateData = await response.json();
    
    if (replicateData.error) throw new Error(replicateData.error);
    if (!replicateData.output || !replicateData.output[0]) throw new Error("No image output generated by the AI.");

    // SUCCESS! Map the output to 'aiImageUrl' to maintain compatibility with your frontend Shopify code.
    const outputUrl = replicateData.output[0];
    console.log(`Generation complete. AI Image URL: ${outputUrl}`);
    
    res.json({ aiImageUrl: outputUrl });

  } catch (error) {
    console.error("AI Generation Error:", error.message);
    res.status(500).json({ error: error.message || "An unexpected error occurred." });
  }
});

app.listen(PORT, () => {
  console.log(`Upgraded Customizer Server running on port ${PORT}`);
});
